// Package correction provides type definitions and mappings for data correction and translation.
// It contains bilingual mappings between Mongolian and English for resources, contract types,
// and document types used in the mining contracts system.
package correction

// Map is a type alias for string-to-string mappings used throughout the correction package.
type Map map[string]string

// Resources maps numeric resource IDs to their Mongolian names.
// These represent various mineral and resource types used in mining contracts.
var Resources = Map{
	"3":   "Агальметолит",
	"4":   "Хуайс",
	"5":   "Шаварлаг шороо",
	"6":   "Бетон зуурмаг",
	"7":   "Хөнгөн цагаан",
	"8":   "Ягаан Болор",
	"9":   "Усан Биндэряа",
	"10":  "Цемент",
	"11":  "Асфальт/Битум",
	"12":  "Барий",
	"13":  "Холимог Металл",
	"14":  "Базальт",
	"15":  "Боксит",
	"16":  "Биндэръяа",
	"17":  "Био Түлш",
	"18":  "Бисмут",
	"19":  "Магнезит",
	"20":  "Битумтай Тослог Нүүрс",
	"21":  "Тоосго",
	"22":  "Борон",
	"23":  "Хүрэн Нүүрс",
	"24":  "Барилгын Материал",
	"25":  "Кадми",
	"26":  "Шавар",
	"27":  "Нүүрс",
	"28":  "Коксжих Нүүрс",
	"29":  "Баяжуулсан Коксжих Нүүрс",
	"30":  "Зэс",
	"31":  "Буталмал Чулуу",
	"32":  "Газрын Тос",
	"33":  "Болор",
	"34":  "Шохой Болон Гөлтгөнө (доломит)",
	"35":  "Хайлуур Жонш",
	"36":  "Төмөр Хромын Хайлш",
	"37":  "Хайлуур Жонш",
	"38":  "Чулуун Нүүрс",
	"39":  "Анар",
	"40":  "Байгалийн хий",
	"41":  "Алт",
	"42":  "Боржин",
	"43":  "Бал Чулуу",
	"44":  "Дайрга",
	"45":  "Элс Хайрга",
	"46":  "Ногоон Боржин",
	"47":  "Гөлтгөнө",
	"48":  "Чулуун Давс",
	"49":  "Төмөр",
	"50":  "Төмрийн Хүдэр",
	"51":  "Төмөрлөг Элс",
	"52":  "Мөсөн Шүү",
	"53":  "Газрын Ховор Металл",
	"54":  "Хар Тугалга",
	"55":  "Шохой",
	"56":  "Шохойн Элс",
	"57":  "Шохойн Чулуу",
	"58":  "Литий",
	"59":  "Магнит",
	"60":  "Манган",
	"61":  "Манганы Хүдэр",
	"62":  "Гантиг",
	"63":  "Төмөрлөгийн/ Коксжих Нүүрс",
	"64":  "Хөшөөний Чулуу",
	"65":  "Гялтгануур",
	"66":  "Молибден",
	"67":  "Шавар",
	"68":  "Байгалийн Хий (хий Болон Шингэн)",
	"69":  "Никель",
	"70":  "Никель Ширэм",
	"71":  "Өнгөт Металл",
	"72":  "Oil",
	"73":  "Шатдаг Занар",
	"74":  "Занар",
	"75":  "Хүдэр",
	"76":  "Тугалга",
	"77":  "Хүлэр",
	"78":  "Перлит",
	"79":  "Фосфат",
	"80":  "Фосфорит",
	"81":  "Полиметалл",
	"82":  "Барилгын Чулуу",
	"83":  "Газрын Ховор Элемент",
	"84":  "Давс",
	"85":  "Байгалийн Элс",
	"86":  "Элсэрхэг Чулуу",
	"87":  "Биндэрьяа",
	"88":  "Хагас Коксжих Нүүрс",
	"89":  "Кварц",
	"90":  "Мөнгө",
	"91":  "Жонш",
	"92":  "Жоншны Баяжмал",
	"93":  "Ган",
	"94":  "Үерийн Чулуу",
	"95":  "Элсэн чихэн",
	"96":  "Хүхэр",
	"97":  "Эрчим Хүчний Нүүрс ",
	"98":  "Цагаан Тугалга",
	"99":  "Титан",
	"100": "Вольфрам/Гянтболд",
	"101": "Боловсруулаагүй Нүүрс",
	"102": "Уран Болон Торийн Хүдэр, Тэдгээрийн Баяжмал",
	"103": "Галт Уулын Шарга",
	"104": "Иттрий",
	"105": "Цеолит",
	"106": "Цайр",
	"107": "Циркон",
	"108": "Тодорхойгүй",
	"109": "Уран",
	"110": "Төмрийн баяжмал",
	"111": "Түгээмэл тархацтай ашигт малтмал",
	"112": "Битум",
	"113": "Висмут",
	"114": "Бусад",
	"115": "Гянболд",
}

// ContractTypesReverse maps Mongolian contract type names to their English equivalents.
// Used for translating contract types when querying or filtering documents.
var ContractTypesReverse = Map{
	"Эд хөрөнгө худалдах, худалдан авах гэрээ": "Asset Sale and Purchase Agreement",
	"Концессийн гэрээ":                         "Concession Agreement",
	"Гэрээнд оруулсан нэмэлт, өөрчлөлт":        "Contract Amendment",
	"Гэрээний хавсралт":                        "Contract Annex",
	"Хөрөнгө өруулалтын гэрээ":                 "Investment Incentive Contract",
	"Хамтарсан үйлдвэр байгуулах гэрээ":        "Joint Venture Agreement",
	"Газар ашиглах тухай гэрээ":                "Land Lease Agreement",
	"Хамтын ажиллагааны санамж бичиг":          "Memorandum of Understanding",
	"Бүтээгдэхүүн хуваах гэрээ":                "Production or Profit Sharing Agreement",
	"Тооцоо нийлсэн протокол":                  "Protocole d'Accord",
	"Үйлчилгээний гэрээ":                       "Service Contract",
	"Тогтвортой байдлын гэрээ":                 "Stabilization Agreements",
	"Дагалдах гэрээ":                           "Sub Contract",
	"Дамжуулан түрээслэх гэрээ":                "Sub-lease",
	"Гэрээний орчуулга":                        "Translated Contract",
	"Орд ашиглах гэрээ":                        "Agreement on exploitation of the deposit",
	"Ашиглалтын өмнөх гэрээ":                   "Pre-mining agreement",
	"Ус ашиглах тухай гэрээ":                   "Contract on water use",
	"Хөрөнгө түрээслэх гэрээ":                  "Lease agreement",
	"Бүтээгдэхүүн борлуулах гэрээ":             "Commodity sales agreement",
	"Барьцааны гэрээ":                          "Pledge agreement",
	"Гол мөрний урсац бүрэлдэх эх, усны сан бүхий газрын хамгаалалтын бүс, ойн сан бүхий газарт ашигт малтмал хайх, ашиглахыг хориглох тухай хуулийн дагуу хийгдэх гэрээ": "Contract under the Law on Prohibiting minerals exploration and exploitation in water heads and protected zone of rivers and forested  areas",
	"Улсын төсвийн хөрөнгөөр хийсэн хайгуулын ажлын зардлын нөхөн төлбөрийн гэрээ":                                                                                        "Reimbursement agreement for minerals exploration funded by state budget",
	"Орон нутагтай хамтран ажиллах гэрээ":                       "Localcooperation agreement",
	"Бүтээн байгуулалтын гэрээ":                                 "Development agreement",
	"Геологийн судалгааны зөвлөх үйлчилгээний гэрээ":            "Consultancy contract on geological research",
	"Газрын тосны эрлийн гэрээ":                                 "Oil prospecting agreement",
	"Бичил уурхайгаар ашигт малтмал олборлох тухай гэрээ":       "Artisanal mining agreement",
	"Төрийн өмчит уул уурхайн компанийн худалдан авалтын гэрээ": "Procurement contracts of state owned enterprises",
	"Бусад": "Other",
	"Эрдэнэс Таван Толгойн OFF-TAKE гэрээнүүд": "Erdenes Tavan Tolgoi OFF-TAKE agreements",
	"Erdenes Tavan Tolgoi OFF-TAKE agreements": "Эрдэнэс Таван Толгойн OFF-TAKE гэрээнүүд",
}

// ContractTypes maps English contract type names to their Mongolian equivalents.
// This is the reverse mapping of ContractTypesReverse, used for displaying
// contract types in the local language.
var ContractTypes = Map{
	"Asset Sale and Purchase Agreement":        "Эд хөрөнгө худалдах, худалдан авах гэрээ",
	"Concession Agreement":                     "Концессийн гэрээ",
	"Contract Amendment":                       "Гэрээнд оруулсан нэмэлт, өөрчлөлт",
	"Contract Annex":                           "Гэрээний хавсралт",
	"Investment Incentive Contract":            "Хөрөнгө өруулалтын гэрээ",
	"Joint Venture Agreement":                  "Хамтарсан үйлдвэр байгуулах гэрээ",
	"Land Lease Agreement":                     "Газар ашиглах тухай гэрээ",
	"Memorandum of Understanding":              "Хамтын ажиллагааны санамж бичиг",
	"Production or Profit Sharing Agreement":   "Бүтээгдэхүүн хуваах гэрээ",
	"Protocole d'Accord":                       "Тооцоо нийлсэн протокол",
	"Service Contract":                         "Үйлчилгээний гэрээ",
	"Stabilization Agreements":                 "Тогтвортой байдлын гэрээ",
	"Sub Contract":                             "Дагалдах гэрээ",
	"Sub-lease":                                "Дамжуулан түрээслэх гэрээ",
	"Translated Contract":                      "Гэрээний орчуулга",
	"Agreement on exploitation of the deposit": "Орд ашиглах гэрээ",
	"Pre-mining agreement":                     "Ашиглалтын өмнөх гэрээ",
	"Contract on water use":                    "Ус ашиглах тухай гэрээ",
	"Lease agreement":                          "Хөрөнгө түрээслэх гэрээ",
	"Commodity sales agreement":                "Бүтээгдэхүүн борлуулах гэрээ",
	"Pledge agreement":                         "Барьцааны гэрээ",
	"Contract under the Law on Prohibiting minerals exploration and exploitation in water heads and protected zone of rivers and forested  areas": "Гол мөрний урсац бүрэлдэх эх, усны сан бүхий газрын хамгаалалтын бүс, ойн сан бүхий газарт ашигт малтмал хайх, ашиглахыг хориглох тухай хуулийн дагуу хийгдэх гэрээ",
	"Reimbursement agreement for minerals exploration funded by state budget":                                                                     "Улсын төсвийн хөрөнгөөр хийсэн хайгуулын ажлын зардлын нөхөн төлбөрийн гэрээ",
	"Localcooperation agreement":                       "Орон нутагтай хамтран ажиллах гэрээ",
	"Development agreement":                            "Бүтээн байгуулалтын гэрээ",
	"Consultancy contract on geological research":      "Геологийн судалгааны зөвлөх үйлчилгээний гэрээ",
	"Oil prospecting agreement":                        "Газрын тосны эрлийн гэрээ",
	"Artisanal mining agreement":                       "Бичил уурхайгаар ашигт малтмал олборлох тухай гэрээ",
	"Procurement contracts of state owned enterprises": "Төрийн өмчит уул уурхайн компанийн худалдан авалтын гэрээ",
	"Other":   "Бусад",
	"test123": "Тест123",
	"test":    "Тест",
	// Эрдэнэс Таван Толгойн OFF-TAKE гэрээнүүд
	"Erdenes Tavan Tolgoi OFF-TAKE agreements": "Эрдэнэс Таван Толгойн OFF-TAKE гэрээнүүд",
	"Эрдэнэс Таван Толгойн OFF-TAKE гэрээнүүд": "Erdenes Tavan Tolgoi OFF-TAKE agreements",
}

// DocumentTypes maps English document type names to their Mongolian equivalents.
// Used for displaying document types in the user interface.
var DocumentTypes = Map{
	"Contract":                                   "Гэрээ",
	"Model Contract":                             "Загвар гэрээ",
	"Environmental Impact Assessment":            "Байгаль орчинд нөлөөлөх байдлын үнэлгээ",
	"Strategic environmental impact assessment":  "Байгаль орчны стратегийн үнэлгээ",
	"Cumulative environmental impact assessment": "Хуримтлагдах нөлөөллийн үнэлгээ",
	"Feasiblity Study":                           "Техник-эдийн засгийн үндэслэл",
	"Financial information":                      "Санхүүгийн мэдээлэл",
	"Notice":                                     "Мэдэгдэл",
	"Project Plan":                               "Төслийн төлөвлөгөө",
	"Social Agreement":                           "Нийгмийн гэрээ",
	"Social Impact Assessment":                   "Нийгмийн нөлөөллийн үнэлгээ",
	"Stabilization certificate":                  "Тогтворжуулах гэрчилгээ",
	"Environmental management plan":              "Байгаль орчны менежментийн төлөвлөгөө",
	"Environmental monitoring program":           "Орчны хяналт-шинжилгээний хөтөлбөр",
	"Environmental management report":            "Байгаль орчны менежментийн тайлан",
	"Complaints and decisions":                   "Гомдол шийдвэр",
	"Tender":                                     "Сонгон шалгуулалттай холбоотой баримт бичиг",
	"Project closure plan":                       "Уурхайн хаалтын төлөвлөгөө",
	"Commodity sales agreements":                 "Бүтээгдэхүүн борлуулалтын гэрээ",
	"Exploitation Permit/License":                "Ашиглалтын тусгай зөвшөөрөл",
	"Exploration Permit/License":                 "Хайгуулын тусгай зөвшөөрөл",
	"Other":                                      "Бусад",
}

// DocumentTypesReverse maps Mongolian document type names to their English equivalents.
// Used for translating document types when querying or filtering documents.
var DocumentTypesReverse = Map{
	"Гэрээ":        "Contract",
	"Загвар гэрээ": "Model Contract",
	"Байгаль орчинд нөлөөлөх байдлын үнэлгээ":     "Environmental Impact Assessment",
	"Байгаль орчны стратегийн үнэлгээ":            "Strategic environmental impact assessment",
	"Хуримтлагдах нөлөөллийн үнэлгээ":             "Cumulative environmental impact assessment",
	"Техник-эдийн засгийн үндэслэл":               "Feasiblity Study",
	"Санхүүгийн мэдээлэл":                         "Financial information",
	"Мэдэгдэл":                                    "Notice",
	"Төслийн төлөвлөгөө":                          "Project Plan",
	"Нийгмийн гэрээ":                              "Social Agreement",
	"Нийгмийн нөлөөллийн үнэлгээ":                 "Social Impact Assessment",
	"Тогтворжуулах гэрчилгээ":                     "Stabilization certificate",
	"Байгаль орчны менежментийн төлөвлөгөө":       "Environmental management plan",
	"Орчны хяналт-шинжилгээний хөтөлбөр":          "Environmental monitoring program",
	"Байгаль орчны менежментийн тайлан":           "Environmental management report",
	"Гомдол шийдвэр":                              "Complaints and decisions",
	"Сонгон шалгуулалттай холбоотой баримт бичиг": "Tender",
	"Уурхайн хаалтын төлөвлөгөө":                  "Project closure plan",
	"Бүтээгдэхүүн борлуулалтын гэрээ":             "Commodity sales agreements",
	"Ашиглалтын тусгай зөвшөөрөл":                 "Exploitation Permit/License",
	"Хайгуулын тусгай зөвшөөрөл":                  "Exploration Permit/License",
	"Бусад": "Other",
}
